# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 243e8a9d62501a53ae26698f2bc0c378062546955a492acb07ab936d5e19407f965799c3f329a5256cd22f1a349a688afb6917e02b68b66ad7bcf577b02eb1fe

test:
  secret_key_base: 25c11078baadf6ffc0bf4d1c9390262cee6746988b451f0f5465846448db291adec69c37a76cade7a1d402b9b80472dc81a7fb0ccdec97c97b2962e8b531fde7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
